name: SayHello

on: 
  push:
    branches:
      - main
      
  jobs:
    welcome:
      runs-on: ubuntu-latest
      
      steps:
      - name: Dowload your code
        use: actions/checkout@v2 
        
      - name: Say something
        run: echo "hello word"
